In [148]:
#Swagatam Bera
#Encryptix recommendation system

import numpy as np
import pandas as pd

In [149]:
books_read=pd.read_csv("C:/Users/beraj/OneDrive/Desktop/Amazon_popular_books_dataset.csv")

In [150]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,Emily Brontë,13451,Amazon,Wuthering Heights (Collins Classics),"[""Books"",""Literature & Fiction"",""Genre Fiction""]"
1,9.78E+12,Drew Daywalt,16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"[""Books"",""Children's Books"",""Literature & Fict..."
2,8183988,Bernard Cornwell,11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"[""Books"",""Literature & Fiction"",""Genre Fiction""]"
3,8305838,David Walliams,15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"[""Books"",""Children's Books"",""Literature & Fict..."
4,8375526,Caroline Hirons,10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"[""Books"",""Crafts, Hobbies & Home"",""Home Improv..."
...,...,...,...,...,...,...
2264,NaN,Jess Lourey,17923,Amazon,Unspeakable Things,"[""Books"",""Mystery, Thriller & Suspense"",""Thril..."
2265,NaN,"Heidi Murkoff (Author, Narrator), Meeghan Hola...",25304,Amazon,What to Expect When You’re Expecting,"[""Books"",""Health, Fitness & Dieting"",""Women's ..."
2266,NaN,"Clea Shearer (Author, Narrator), Joanna Teplin...",11040,Amazon,The Home Edit: A Guide to Organizing and Reali...,"[""Books"",""Crafts, Hobbies & Home"",""Home Improv..."
2267,NaN,"Lisa Jewell (Author), Tamaryn Payne (Narrator)...",28030,Amazon,The Family Upstairs: A Novel,"[""Books"",""Mystery, Thriller & Suspense"",""Thril..."
2268,NaN,"Elton John (Author, Narrator), Taron Egerton (...",18141,Amazon,Me: Elton John Official Autobiography,"[""Books"",""Arts & Photography"",""Music"",""Musical..."

In [151]:
books_read.isnull().sum()

ISBN10           840
Author             1
reviews_count      0
seller_name        0
Title              0
categories         0
dtype: int64

In [152]:
books_read.dropna(inplace=True)

In [153]:
import ast

In [154]:
books_read['categories'] = books_read['categories'].str.replace('[', '').str.replace(']', '')

In [155]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,Emily Brontë,13451,Amazon,Wuthering Heights (Collins Classics),"""Books"",""Literature & Fiction"",""Genre Fiction"""
1,9.78E+12,Drew Daywalt,16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"""Books"",""Children's Books"",""Literature & Fiction"""
2,8183988,Bernard Cornwell,11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"""Books"",""Literature & Fiction"",""Genre Fiction"""
3,8305838,David Walliams,15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"""Books"",""Children's Books"",""Literature & Fiction"""
4,8375526,Caroline Hirons,10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"""Books"",""Crafts, Hobbies & Home"",""Home Improve..."
...,...,...,...,...,...,...
1424,9389440181,Madeleine L'Engle,10230,Amazon,A Wrinkle in Time,"""Books"",""Children's Books"",""Science Fiction & ..."
1579,1623158087,Amy Ramos,25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"""Books"",""Health, Fitness & Dieting"",""Diseases ..."
1868,1419741853,Jeff Kinney,12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"""Books"",""Children's Books"",""Humor"""
1987,1419741934,Jeff Kinney,10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"""Books"",""Children's Books"",""Humor"""
2038,01602244G,"Lee Child (Author), Dick Hill (Narrator), Rand...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","""Books"",""Mystery, Thriller & Suspense"",""Thrill..."

In [156]:
books_read['categories'] = books_read['categories'].str.replace('"Books",', '')

In [157]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,Emily Brontë,13451,Amazon,Wuthering Heights (Collins Classics),"""Literature & Fiction"",""Genre Fiction"""
1,9.78E+12,Drew Daywalt,16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"""Children's Books"",""Literature & Fiction"""
2,8183988,Bernard Cornwell,11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"""Literature & Fiction"",""Genre Fiction"""
3,8305838,David Walliams,15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"""Children's Books"",""Literature & Fiction"""
4,8375526,Caroline Hirons,10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"""Crafts, Hobbies & Home"",""Home Improvement & D..."
...,...,...,...,...,...,...
1424,9389440181,Madeleine L'Engle,10230,Amazon,A Wrinkle in Time,"""Children's Books"",""Science Fiction & Fantasy"""
1579,1623158087,Amy Ramos,25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"""Health, Fitness & Dieting"",""Diseases & Physic..."
1868,1419741853,Jeff Kinney,12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"""Children's Books"",""Humor"""
1987,1419741934,Jeff Kinney,10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"""Children's Books"",""Humor"""
2038,01602244G,"Lee Child (Author), Dick Hill (Narrator), Rand...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","""Mystery, Thriller & Suspense"",""Thrillers & Su..."

In [158]:
books_read['categories'] = books_read['categories'].str.replace('"', '')

In [159]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,Emily Brontë,13451,Amazon,Wuthering Heights (Collins Classics),"Literature & Fiction,Genre Fiction"
1,9.78E+12,Drew Daywalt,16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"Children's Books,Literature & Fiction"
2,8183988,Bernard Cornwell,11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"Literature & Fiction,Genre Fiction"
3,8305838,David Walliams,15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"Children's Books,Literature & Fiction"
4,8375526,Caroline Hirons,10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"Crafts, Hobbies & Home,Home Improvement & Design"
...,...,...,...,...,...,...
1424,9389440181,Madeleine L'Engle,10230,Amazon,A Wrinkle in Time,"Children's Books,Science Fiction & Fantasy"
1579,1623158087,Amy Ramos,25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"Health, Fitness & Dieting,Diseases & Physical ..."
1868,1419741853,Jeff Kinney,12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"Children's Books,Humor"
1987,1419741934,Jeff Kinney,10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"Children's Books,Humor"
2038,01602244G,"Lee Child (Author), Dick Hill (Narrator), Rand...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","Mystery, Thriller & Suspense,Thrillers & Suspe..."

In [160]:
def g(books_read):
    books_read['categories'] = books_read['categories'].str.split(',')
    return books_read

In [161]:
books_read=g(books_read)

In [162]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,Emily Brontë,13451,Amazon,Wuthering Heights (Collins Classics),"[Literature & Fiction, Genre Fiction]"
1,9.78E+12,Drew Daywalt,16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"[Children's Books, Literature & Fiction]"
2,8183988,Bernard Cornwell,11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"[Literature & Fiction, Genre Fiction]"
3,8305838,David Walliams,15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"[Children's Books, Literature & Fiction]"
4,8375526,Caroline Hirons,10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"[Crafts, Hobbies & Home, Home Improvement & D..."
...,...,...,...,...,...,...
1424,9389440181,Madeleine L'Engle,10230,Amazon,A Wrinkle in Time,"[Children's Books, Science Fiction & Fantasy]"
1579,1623158087,Amy Ramos,25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"[Health, Fitness & Dieting, Diseases & Physic..."
1868,1419741853,Jeff Kinney,12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"[Children's Books, Humor]"
1987,1419741934,Jeff Kinney,10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"[Children's Books, Humor]"
2038,01602244G,"Lee Child (Author), Dick Hill (Narrator), Rand...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","[Mystery, Thriller & Suspense, Thrillers & Su..."

In [163]:
def ga(books_read):
    books_read['Author'] = books_read['Author'].apply(lambda x: x.split(','))


ga(books_read)

In [164]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories
0,7350813,[Emily Brontë],13451,Amazon,Wuthering Heights (Collins Classics),"[Literature & Fiction, Genre Fiction]"
1,9.78E+12,[Drew Daywalt],16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"[Children's Books, Literature & Fiction]"
2,8183988,[Bernard Cornwell],11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"[Literature & Fiction, Genre Fiction]"
3,8305838,[David Walliams],15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"[Children's Books, Literature & Fiction]"
4,8375526,[Caroline Hirons],10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"[Crafts, Hobbies & Home, Home Improvement & D..."
...,...,...,...,...,...,...
1424,9389440181,[Madeleine L'Engle],10230,Amazon,A Wrinkle in Time,"[Children's Books, Science Fiction & Fantasy]"
1579,1623158087,[Amy Ramos],25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"[Health, Fitness & Dieting, Diseases & Physic..."
1868,1419741853,[Jeff Kinney],12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"[Children's Books, Humor]"
1987,1419741934,[Jeff Kinney],10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"[Children's Books, Humor]"
2038,01602244G,"[Lee Child (Author), Dick Hill (Narrator), R...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","[Mystery, Thriller & Suspense, Thrillers & Su..."

In [165]:
books_read['tags']=books_read['categories']+books_read['Author']

In [166]:
books_read

,ISBN10,Author,reviews_count,seller_name,Title,categories,tags
0,7350813,[Emily Brontë],13451,Amazon,Wuthering Heights (Collins Classics),"[Literature & Fiction, Genre Fiction]","[Literature & Fiction, Genre Fiction, Emily Br..."
1,9.78E+12,[Drew Daywalt],16628,VMG Books & Media,THE DAYS THE CRAYONS QUIT,"[Children's Books, Literature & Fiction]","[Children's Books, Literature & Fiction, Drew ..."
2,8183988,[Bernard Cornwell],11275,Reuseaworld,War Lord: Book 13 (The Last Kingdom Series),"[Literature & Fiction, Genre Fiction]","[Literature & Fiction, Genre Fiction, Bernard ..."
3,8305838,[David Walliams],15520,Bahamut Media,Code Name Bananas: The hilarious and epic new ...,"[Children's Books, Literature & Fiction]","[Children's Books, Literature & Fiction, David..."
4,8375526,[Caroline Hirons],10884,KathrynAshleyGallery,Skincare: The award-winning ultimate no-nonsen...,"[Crafts, Hobbies & Home, Home Improvement & D...","[Crafts, Hobbies & Home, Home Improvement & D..."
...,...,...,...,...,...,...,...
1424,9389440181,[Madeleine L'Engle],10230,Amazon,A Wrinkle in Time,"[Children's Books, Science Fiction & Fantasy]","[Children's Books, Science Fiction & Fantasy, ..."
1579,1623158087,[Amy Ramos],25596,Amazon,The Complete Ketogenic Diet for Beginners: You...,"[Health, Fitness & Dieting, Diseases & Physic...","[Health, Fitness & Dieting, Diseases & Physic..."
1868,1419741853,[Jeff Kinney],12027,Goodwill of Dayton Ohio,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"[Children's Books, Humor]","[Children's Books, Humor, Jeff Kinney]"
1987,1419741934,[Jeff Kinney],10239,Clean Earth Books,The Third Wheel (Diary of a Wimpy Kid #7),"[Children's Books, Humor]","[Children's Books, Humor, Jeff Kinney]"
2038,01602244G,"[Lee Child (Author), Dick Hill (Narrator), R...",10626,Amazon,"Echo Burning: Jack Reacher, Book 5","[Mystery, Thriller & Suspense, Thrillers & Su...","[Mystery, Thriller & Suspense, Thrillers & Su..."

In [167]:
new_dataframe=books_read[['ISBN10','Title','tags']]

In [168]:
new_dataframe

,ISBN10,Title,tags
0,7350813,Wuthering Heights (Collins Classics),"[Literature & Fiction, Genre Fiction, Emily Br..."
1,9.78E+12,THE DAYS THE CRAYONS QUIT,"[Children's Books, Literature & Fiction, Drew ..."
2,8183988,War Lord: Book 13 (The Last Kingdom Series),"[Literature & Fiction, Genre Fiction, Bernard ..."
3,8305838,Code Name Bananas: The hilarious and epic new ...,"[Children's Books, Literature & Fiction, David..."
4,8375526,Skincare: The award-winning ultimate no-nonsen...,"[Crafts, Hobbies & Home, Home Improvement & D..."
...,...,...,...
1424,9389440181,A Wrinkle in Time,"[Children's Books, Science Fiction & Fantasy, ..."
1579,1623158087,The Complete Ketogenic Diet for Beginners: You...,"[Health, Fitness & Dieting, Diseases & Physic..."
1868,1419741853,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),"[Children's Books, Humor, Jeff Kinney]"
1987,1419741934,The Third Wheel (Diary of a Wimpy Kid #7),"[Children's Books, Humor, Jeff Kinney]"
2038,01602244G,"Echo Burning: Jack Reacher, Book 5","[Mystery, Thriller & Suspense, Thrillers & Su..."

In [169]:
new_dataframe['tags']= new_dataframe['tags'].apply(lambda x:' '.join(x))

C:\Users\beraj\AppData\Local\Temp\ipykernel_20444\303769069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['tags']= new_dataframe['tags'].apply(lambda x:' '.join(x))

In [170]:
new_dataframe

,ISBN10,Title,tags
0,7350813,Wuthering Heights (Collins Classics),Literature & Fiction Genre Fiction Emily Brontë
1,9.78E+12,THE DAYS THE CRAYONS QUIT,Children's Books Literature & Fiction Drew Day...
2,8183988,War Lord: Book 13 (The Last Kingdom Series),Literature & Fiction Genre Fiction Bernard Cor...
3,8305838,Code Name Bananas: The hilarious and epic new ...,Children's Books Literature & Fiction David Wa...
4,8375526,Skincare: The award-winning ultimate no-nonsen...,Crafts Hobbies & Home Home Improvement & Desi...
...,...,...,...
1424,9389440181,A Wrinkle in Time,Children's Books Science Fiction & Fantasy Mad...
1579,1623158087,The Complete Ketogenic Diet for Beginners: You...,Health Fitness & Dieting Diseases & Physical ...
1868,1419741853,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),Children's Books Humor Jeff Kinney
1987,1419741934,The Third Wheel (Diary of a Wimpy Kid #7),Children's Books Humor Jeff Kinney
2038,01602244G,"Echo Burning: Jack Reacher, Book 5",Mystery Thriller & Suspense Thrillers & Suspe...

In [171]:
new_dataframe['tags']= new_dataframe['tags'].apply(lambda x:x.lower())

C:\Users\beraj\AppData\Local\Temp\ipykernel_20444\3870462640.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['tags']= new_dataframe['tags'].apply(lambda x:x.lower())

In [172]:
new_dataframe

,ISBN10,Title,tags
0,7350813,Wuthering Heights (Collins Classics),literature & fiction genre fiction emily brontë
1,9.78E+12,THE DAYS THE CRAYONS QUIT,children's books literature & fiction drew day...
2,8183988,War Lord: Book 13 (The Last Kingdom Series),literature & fiction genre fiction bernard cor...
3,8305838,Code Name Bananas: The hilarious and epic new ...,children's books literature & fiction david wa...
4,8375526,Skincare: The award-winning ultimate no-nonsen...,crafts hobbies & home home improvement & desi...
...,...,...,...
1424,9389440181,A Wrinkle in Time,children's books science fiction & fantasy mad...
1579,1623158087,The Complete Ketogenic Diet for Beginners: You...,health fitness & dieting diseases & physical ...
1868,1419741853,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),children's books humor jeff kinney
1987,1419741934,The Third Wheel (Diary of a Wimpy Kid #7),children's books humor jeff kinney
2038,01602244G,"Echo Burning: Jack Reacher, Book 5",mystery thriller & suspense thrillers & suspe...

In [173]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=8500,stop_words='english')

In [174]:
cv.fit_transform(new_dataframe['tags']).toarray().shape

(1428, 1366)

In [175]:
vectors=cv.fit_transform(new_dataframe['tags']).toarray()

In [176]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [177]:
len(cv.get_feature_names_out())

1366

In [178]:
from nltk.stem.porter import PorterStemmer 
ps = PorterStemmer()

In [179]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return" ".join(y)

In [180]:
new_dataframe['tags']= new_dataframe['tags'].apply(stem)

C:\Users\beraj\AppData\Local\Temp\ipykernel_20444\2511283695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe['tags']= new_dataframe['tags'].apply(stem)

In [181]:
new_dataframe

,ISBN10,Title,tags
0,7350813,Wuthering Heights (Collins Classics),literatur & fiction genr fiction emili brontë
1,9.78E+12,THE DAYS THE CRAYONS QUIT,children' book literatur & fiction drew daywalt
2,8183988,War Lord: Book 13 (The Last Kingdom Series),literatur & fiction genr fiction bernard cornwel
3,8305838,Code Name Bananas: The hilarious and epic new ...,children' book literatur & fiction david walliam
4,8375526,Skincare: The award-winning ultimate no-nonsen...,craft hobbi & home home improv & design caroli...
...,...,...,...
1424,9389440181,A Wrinkle in Time,children' book scienc fiction & fantasi madele...
1579,1623158087,The Complete Ketogenic Diet for Beginners: You...,health fit & diet diseas & physic ailment ami ...
1868,1419741853,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),children' book humor jeff kinney
1987,1419741934,The Third Wheel (Diary of a Wimpy Kid #7),children' book humor jeff kinney
2038,01602244G,"Echo Burning: Jack Reacher, Book 5",mysteri thriller & suspens thriller & suspens ...

In [182]:
from sklearn.metrics.pairwise import cosine_similarity

In [183]:
cosine_similarity (vectors)

array([[1.        , 0.4330127 , 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.4330127 , 1.        , 0.4330127 , ..., 0.36514837, 0.36514837,
        0.        ],
       [0.75      , 0.4330127 , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.36514837, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.36514837, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [184]:
cosine_similarity (vectors).shape

(1428, 1428)

In [185]:
def recommend (book):
    book_index=new_dataframe[new_dataframe['Title']==book].index[0]
    distances=cosine_similarity (vectors)[book_index]
    names_of_books=sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in names_of_books:
        print(new_dataframe.iloc[i[0]].Title)

In [186]:
recommend('The Silmarillion')

J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings
The Hobbit and The Lord of the Rings
The Invisible Life of Addie LaRue, Special Edition
Behind Closed Doors: A Novel
The Atlantis Gene: A Thriller (The Origin Mystery, Book 1)

In [187]:
recommend('West with Giraffes: A Novel')

Diary of a Minecraft Zombie Book 1: A Scare of a Dare
West with Giraffes: A Novel
Wuthering Heights (Collins Classics)
THE DAYS THE CRAYONS QUIT
War Lord: Book 13 (The Last Kingdom Series)